on:
  workflow_call:
    inputs:
      package_folder:
        required: true
        type: string
      files_to_ignore:
        required: false
        type: string
        default: ""
      coverage_args:
        required: false
        type: string
        default: ""

env:
  package_folder: ${{ inputs.package_folder }}
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Cache build
        uses: ./.github/actions/cache_foundry_build
        with:
          package_folder: ${{ env.package_folder }}
          foundry_profile: coverage

      - name: Run Forge coverage
        run: cd $package_folder && forge coverage --report lcov ${{ inputs.coverage_args }}
        env:
          TENDERLY_KEY: ${{ secrets.TENDERLY_KEY }}
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          CONDUIT_KEY: ${{ secrets.CONDUIT_KEY }}

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Filter files to ignore
        run: |
          cd ./${{ env.package_folder }} && lcov --rc lcov_branch_coverage=1 \
          --remove lcov.info \
          --output-file lcov.info "*node_modules*" "*test*" "*script*" ${{ inputs.files_to_ignore }}

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v2
        with:
          coverage-files: ./${{ env.package_folder }}/lcov.info
          minimum-coverage: 87
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./${{ env.package_folder }}
